### PR TITLE
Update the dtd testers with GPU for the newer, simpler GPU DTD queuing

### PR DESCRIPTION
**Pull request by abouteiller**
Dplasma is using the old style DTD with GPU. This is doing it the new way (also it doesn't crash, so there's that).

### CODE REVIEW

**Comment by abouteiller** [comment]
@therault this computes the wrong answer, I suspect because using cublasZgemm (v1) on the `cuda_stream->cuda_stream` rather than the replacement system with the registered handles.

**Comment by bosilca** [comment]
As discussed on 03/31/23 this need to be updated and the result need to be validated.

**Comment by therault** [comment]
See previous comment

**Comment by abouteiller** [comment]
This now computes the correct answer for N=3*NB (i.e., only one GEMM) but still computes the wrong answer for N=4*NB (i.e.,  4 gemms)

**Comment by bosilca** [comment]
Similar work has been completed in #94

**Pull request closed without merging**
